"""initial schema

Revision ID: 216b02aa5afa
Revises: 
Create Date: 2026-05-08 19:42:42.974918

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '216b02aa5afa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('admin', 'family', 'child', 'guest', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('assets',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.Enum('image', 'video', 'audio', 'note', 'document', 'voice_note', 'link', 'archive', name='asset_type'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True, comment='When the moment depicted by the asset actually happened.'),
    sa.Column('permission_scope', sa.Enum('private', 'family', 'shared', 'public_link', name='permission_scope'), server_default='private', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_type'), 'assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_assets_captured_at'), 'assets', ['captured_at'], unique=False)
    op.create_index(op.f('ix_assets_owner_id'), 'assets', ['owner_id'], unique=False)
    op.create_table('asset_versions',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False, comment='Object key inside the S3-compatible bucket.'),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='EXIF / mutagen / ffprobe payload extracted by the worker.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_versions_asset_id'), 'asset_versions', ['asset_id'], unique=False)
    op.create_table('timeline_entries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('asset_added', 'event', 'activity', name='timeline_entry_kind'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_entries_asset_id'), 'timeline_entries', ['asset_id'], unique=False)
    op.create_index(op.f('ix_timeline_entries_kind'), 'timeline_entries', ['kind'], unique=False)
    op.create_index(op.f('ix_timeline_entries_occurred_at'), 'timeline_entries', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_timeline_entries_user_id'), 'timeline_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_entries_user_id'), table_name='timeline_entries')
    op.drop_index(op.f('ix_timeline_entries_occurred_at'), table_name='timeline_entries')
    op.drop_index(op.f('ix_timeline_entries_kind'), table_name='timeline_entries')
    op.drop_index(op.f('ix_timeline_entries_asset_id'), table_name='timeline_entries')
    op.drop_table('timeline_entries')
    op.drop_index(op.f('ix_asset_versions_asset_id'), table_name='asset_versions')
    op.drop_table('asset_versions')
    op.drop_index(op.f('ix_assets_owner_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_captured_at'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_type'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

    # Native PG ENUM types are not auto-dropped by drop_table; do it explicitly
    # so a clean re-upgrade does not fail with "type already exists".
    for enum_name in (
        "timeline_entry_kind",
        "permission_scope",
        "asset_type",
        "user_role",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
